name: 'projet_cc'
version: '1.0.0'
config-version: 2

profile: 'Projet CC'

model-paths: ["models"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  projet_cc:
    +materialized: view
