-- remove TX_ME column due to too many NULL values
-- parse date AAAAMM
-- extract year and month from AAAAMM
-- remove lines where quality codes = 2 (= not validated)
-- exclude data before 1952 because data is very sparse

WITH base AS (
    SELECT
    NUM_POSTE,
    PARSE_DATE('%Y%m%d',CONCAT(AAAAMM,'01')) as AAAAMM,
    CAST(LEFT(AAAAMM, 4) AS INT64) AS ANNEE,
    CAST(RIGHT(AAAAMM, 2) AS INT64) AS MOIS,  
    TX,QTX,NBTX,
    TXAB,QTXAB,PARSE_DATE('%Y%m%d',CONCAT(AAAAMM,TXDAT)) as TXDAT,
    TXMIN,QTXMIN,PARSE_DATE('%Y%m%d',CONCAT(AAAAMM,TXMINDAT)) as TXMINDAT,
    NBJTX0,
    NBJTX25,
    NBJTX30,
    NBJTX35,
    NBJTXI20,
    NBJTXI27,
    NBJTXS32,
    TN,QTN,NBTN,TN_ME,
    TNAB,QTNAB,PARSE_DATE('%Y%m%d',CONCAT(AAAAMM,TNDAT)) as TNDAT,
    TNMAX,QTNMAX,PARSE_DATE('%Y%m%d',CONCAT(AAAAMM,TNMAXDAT)) as TNMAXDAT,
    NBJTN5,
    NBJTN10,
    NBJTNI10,
    NBJTNI15,
    NBJTNI20,
    NBJTNS20,
    NBJTNS25,
    NBJGELEE,
    TAMPLIM,QTAMPLIM,
    TAMPLIAB,QTAMPLIAB,PARSE_DATE('%Y%m%d',CONCAT(AAAAMM,TAMPLIABDAT)) as TAMPLIABDAT,NBTAMPLI,
    TM,QTM,NBTM,
    TMM,QTMM,NBTMM,
    NBJTMS24,
    TMMIN,QTMMIN,PARSE_DATE('%Y%m%d',CONCAT(AAAAMM,TMMINDAT)) as TMMINDAT,
    TMMAX,QTMMAX,PARSE_DATE('%Y%m%d',CONCAT(AAAAMM,TMMAXDAT)) as TMMAXDAT
    FROM `cc-reunion.MENS_meteofrance.MENSQ_974_1900-2025`
)
SELECT *
FROM base
WHERE QTX != 2
AND QTXAB != 2
AND QTXMIN != 2
AND QTN != 2
AND QTNAB != 2
AND QTNMAX != 2
AND QTAMPLIM != 2
AND QTAMPLIAB != 2
AND QTMM != 2
AND QTMMIN != 2
AND QTMMAX != 2
AND ANNEE >= 1952